name: test
on:
  push:
    branches:
      - "**"

jobs:
  echo1:
    runs-on: self-hosted
    steps:
      - name: echo echo echo
        run: |
          echo 1
  echo2:
    runs-on: self-hosted
    steps:
      - name: echo echo echo
        run: |
          echo 2
  echo3:
    runs-on: self-hosted
    steps:
      - name: echo echo echo
        run: |
          echo 3
  echo4:
    runs-on: self-hosted
    steps:
      - name: echo echo echo
        run: |
          echo 4
  echo5:
    runs-on: self-hosted
    steps:
      - name: echo echo echo
        run: |
          echo 5
  echo6:
    runs-on: self-hosted
    steps:
      - name: echo echo echo
        run: |
          echo 6
