name: test
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: setup-lxd
       run: |
        sudo snap install lxd
        sudo chmod o+g '/var/snap/lxd/common/lxd/unix.socket'
        cat <<EOF | lxd init --preseed
        storage_pools:
        - name: default
          driver: dir
        networks:
        - name: lxdbr0
          type: bridge
          config:
            ipv4.address: auto
            ipv6.address: none
        profiles:
        - name: default
          devices:
            root:
              path: /
              pool: default
              type: disk
        EOF
        lxc profile device add default eth0 nic name=eth0 network=lxdbr0
     - name: setup-packer
       run: |
         sudo apt-get install -y wget unzip
         sudo curl -L -O https://releases.hashicorp.com/packer/1.7.0/packer_1.7.0_linux_amd64.zip
         sudo unzip packer_1.7.0_linux_amd64.zip
         sudo mv ./packer /tmp/packer
         sudo rm -f ./packer_1.7.0_linux_amd64.zip
     - name: Delete unused file
       run: |
         sudo rm -rf /opt/
         sudo rm -rf /usr/local/*
         sudo rm -rf /usr/local/.ghcup
         sudo rm -rf /usr/lib/jvm /usr/lib/google-cloud-sdk
         sudo rm -rf /home/runneradmin /home/linuxbrew
         sudo rm -rf /home/runner/runners/*.tar.gz
         #sudo rm -rf /home/runner/.*
         # ignore /var/run, snap lxd packages, apt
         sudo ls /var/**/** | grep ":" | tr -d ":" | grep -Ev "/var/run|/var/snap/lxd|/var/lib/snapd|/var/lib/dpkg" |  xargs -I%% sudo rm -rf %%
         # ignore /usr/share/dpkg
         ls /usr/share/ | grep -vE "dpkg|debconf" | xargs -I%% sudo rm -rf /usr/share/%%
     - name: Clone actions/virtual-environments
       id: clone
       run: |
         git clone --depth=1 https://github.com/actions/virtual-environments
         cd virtual-environments
         echo "::set-output name=dir::$(pwd)"
         echo "::set-output name=virtual-environments-hash::$(git rev-parse --short HEAD)"
         echo "::set-output name=build-date::$(date '+%Y%m%d')"
     - name: Apply LXD patch
       run: |
         patch -p1 < ../lxd.patch
       working-directory: ${{ steps.clone.outputs.dir }}
     - name: Prepare packer-plugin-lxd
       run: |
         wget http://${{ secrets.DEPLOY_HOST }}/packer-plugin-lxd
         chmod +x ./packer-plugin-lxd
       working-directory: ${{ steps.clone.outputs.dir }}
     - name: Display space
       run: |
         set -x

         sudo df -h
         sudo du -scm --exclude=/proc/* /*
     - name: packer build packer.json
       run: |
         /tmp/packer build -color=false -on-error=abort images/linux/ubuntu2004.json
       working-directory: ${{ steps.clone.outputs.dir }}
       env:
         PACKER_LOG: 1
     - name: Stop container
       run: lxc stop packer-lxd
     - name: Remove swap
       run: |
         sudo swapoff /mnt/swapfile
         sudo rm -rf /mnt/swapfile
     - name: distrobuilder
       run: |
         wget http://${{ secrets.DEPLOY_HOST }}/distrobuilder
         wget http://${{ secrets.DEPLOY_HOST }}/db.yaml
         chmod +x ./distrobuilder

         sudo mkdir -p /mnt/cache
         sudo mkdir -p /mnt/output
         sudo ./distrobuilder pack-lxd db.yaml "/var/snap/lxd/common/lxd/storage-pools/default/containers/packer-lxd" /mnt/output --cache-dir /mnt/cache
         
         set -x
         ls -l /mnt/output
     - name: Display space
       run: |
         set -x

         sudo df -h
         sudo du -scm --exclude=/proc/* /*
     - name: Upload artifact
       uses: actions/upload-artifact@v2
       with:
         name: virtual-environments-lxd-${{ steps.clone.outputs.virtual-environments-hash }}-${{ steps.clone.outputs.build-date }}
         path: /mnt/output/*
         retention-days: 5
     - name: Run tmate
       uses: mxschmitt/action-tmate@v3
       if: always()
