name: test
on:
  push:
    branches:
      - "**"

jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - uses: whywaita/setup-lxd@0d3b321443c5d287a00bc14097c293fa212b3ab5
        with:
          lxd_version: 2.0/stable
      - uses: actions/checkout@v2
      - run: |
          lxc launch ubuntu:focal instance
          sleep 5
          lxc exec instance -- dig github.com
      - uses: mxschmitt/action-tmate@v3
        if: ${{ always() }}
