name: test
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  echo1:
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v4
     - run: |
         cat /proc/cpuinfo | grep kvm
     - uses: hashicorp/setup-packer@v2.0.0
     - run: packer --help
     - name: Run tmate
       uses: mxschmitt/action-tmate@v3
       if: always()
