name: test
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: whywaita/setup-lxd@v1
     - name: setup-packer
       run: |
         sudo apt-get install -y wget unzip
         sudo curl -L -O https://releases.hashicorp.com/packer/1.7.0/packer_1.7.0_linux_amd64.zip
         sudo unzip packer_1.7.0_linux_amd64.zip
         sudo mv ./packer /tmp/packer
     - name: Delete unused file
       run: |
         sudo rm -rf /opt/
         sudo rm -rf /usr/local/*
         sudo rm -rf /usr/local/.ghcup
         sudo rm -rf /home/runneradmin /home/linuxbrew
         #sudo rm -rf /home/runner/.*
         # ignore /var/run, snap lxd packages, apt
         sudo ls /var/**/** | grep ":" | tr -d ":" | grep -Ev "/var/run|/var/snap/lxd|/var/lib/snapd|/var/lib/dpkg" |  xargs -I%% sudo rm -rf %%
         # ignore /usr/share/dpkg
         ls /usr/share/ | grep -v dpkg | xargs -I%% sudo rm -rf /usr/share/%%
     - uses: easimon/maximize-build-space@master
       with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-haskell: 'true'
          emove-android: 'true'
     - name: Clone actions/virtual-environments
       id: clone
       run: |
         git clone https://github.com/actions/virtual-environments
         cd virtual-environments
         echo "::set-output name=dir::$(pwd)"
         echo "::set-output name=virtual-environments-hash::$(git rev-parse --short HEAD)"
         echo "::set-output name=build-date::$(date '+%Y%m%d')"
         git clone https://github.com/whywaita/virtual-environments-lxd
     - name: Apply LXD patch
       run: |
         patch -p1 < virtual-environments-lxd/lxd.patch
       working-directory: ${{ steps.clone.outputs.dir }}
     - name: packer build packer.json
       run: |
         /tmp/packer build -color=false -on-error=abort images/linux/ubuntu2004.json
       working-directory: ${{ steps.clone.outputs.dir }}
       env:
         PACKER_LOG: 1
     - name: Run tmate
       uses: mxschmitt/action-tmate@v3
       if: always()
