name: test
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  echo1:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: whywaita/setup-lxd@v1
      - uses: mxschmitt/action-tmate@v3
        if: always()
