name: test
on:
  push:
    branches:
      - "**"

jobs:
  echo1:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        size:
          - 1
          - 3
          - 5
          - 6
          - 10
          - 16
          - 20
    steps:
      - uses: whywaita/setup-lxd@v1
      - uses: actions/checkout@v2
      - run: |
          sudo rm -rf /opt/hostedtoolcache/* /opt/ghc
      - run: |
          mkdir _output
          dd if=/dev/zero of=./_output/artifact bs=1G count=${{ matrix.size }}
      - uses: actions/upload-artifact@v2
        with:
          name: zero
          path: _output
