name: test
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Delete unused file
        run: |
          sudo rm -rf /opt/hostedtoolcache
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/*
          sudo rm -rf /var/lib/docker/*
          # ignore /usr/share/dpkg
          ls /usr/share/ | grep -vE "dpkg" | grep -vE "confmodule|defconf" | xargs -I%% sudo rm -rf /usr/share/%%
      - uses: mxschmitt/action-tmate@v3
