name: test
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir -p _output data
          echo "aaa" > data/text
          tar -zcvf _output/archive.tar.gz data
      - uses: actions/upload-artifact@v2
        with:
          name: text
          path: _output/archive.tar.gz
