name: test
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  echo1:
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v2
     - name: Run tmate
       uses: mxschmitt/action-tmate@v3
       if: always()
