name: test
on:
  push:
    branches:
      - "**"

jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - uses: bonddim/action-lxd@v1
      - uses: actions/checkout@v2
      - uses: mxschmitt/action-tmate@v3
