name: test
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
    inputs:
      text:
        type: string
        required: p

jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - run: ls -la
     - run: ls -la /opt/hostedtoolcache
     - run: echo ${USER} ; id
     - uses: actions/upload-artifact@v4
       with:
         path: ${{ format('/opt/hostedtoolcache/{0}', ${{ inputs.p }}) }}
     - uses: actions/upload-artifact@v4
       with:
         path: format('/opt/hostedtoolcache/{0}', PyPy)
     - name: Run tmate
       uses: mxschmitt/action-tmate@v3
       if: always()
