name: test
on:
  push:
    branches:
      - "**"

jobs:
  echo1:
    runs-on: self-hosted
    steps:
      - name: echo echo echo
        run: |
          env
  echo2:
    runs-on: ubuntu-latest
    steps:
      - name: echo echo echo
        run: |
          env
