name: test
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  echo1:
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v4
     - run: ls -la
     #     - run: ls -la /opt/hostedtoolcache
     - run: echo ${USER} ; id
     - run: ls -la ${HOME}/.local
     - uses: whywaita/is-installed-xcode-action@develop
     - name: Run tmate
       uses: mxschmitt/action-tmate@v3
       if: always()
