name: tmate
on:
  workflow_dispatch:

jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - uses: hashicorp/setup-packer@main
     - name: Run tmate
       uses: mxschmitt/action-tmate@v3
       if: always()
